### PR TITLE
[Web3-Auth-v2.1.4-alpha.1, UAuth-v2.0.1-alpha.1, Core-v2.11.1-alpha.1, React, Vue]: Fix - Package Issues found during docs integration

### LINKED ISSUE #1401: [Bug]: Style Border Radius hardcoded instead of variable
### Current Behavior

the class connecting-container.svelte-1c0xedm has the border-radius defined as 24px (hardcoded value)

### Expected Behavior

the class connecting-container.svelte-1c0xedm should define the border-radius defined as --onboard-border-radius-1 variable, in order to easily manipulate it.

### Steps To Reproduce

Just look at the code

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

N/A

### Package Version

2.10.1

### Node Version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

### PR DESCRIPTION
**Pull request by Adamj1232**
### Description

- Web3-Auth-v2.1.4-alpha.1: Fixes modal z-index([created feature request to expose a `z-index` prop](https://github.com/Web3Auth/web3auth-web/issues/1018))  issue & remove deprecated packages
- UAuth-v2.0.1-alpha.1: Fixes Joi import issue
- Core-v2.10.2-alpha.1, React, Vue : Fixes issue with hardcoded border-radius - Close #1401 

Also updated yarn `check` alias in the root package.json as it was being over ridden by the the [yarn based check command](https://classic.yarnpkg.com/lang/en/docs/cli/check/#toc-yarn-check) that should be deprecated.
I added the command that Yarn recommends replacing `yarn check` with resulting in two new yarn commands aliased:

- `"type-check": "yarn wsrun type-check"`
- `"file-check": "yarn install --check-files"`

Both were added to the GH checklist

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [ ] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [x] I have run `yarn check` & `yarn build` to confirm there are not any associated errors
- [x] This PR passes the Circle CI checks

### CODE REVIEW

File: packages/web3auth/src/index.ts [hunk 1]
```diff
@@ -49,13 +51,30 @@ function web3auth(options: Web3AuthModuleOptions): WalletInit {
...
+      const web3authCoreOptions = {
         ...options,
         ...getChainConfig(currentChain)
       }
 
-      let web3auth = new Web3Auth(web3authOptions)
-
+      let web3auth = new Web3Auth(web3authCoreOptions)
+
+      // There is no exposed z-index setter so we must set through modal events
```
Comment (taylorjdawson) [inline packages/web3auth/src/index.ts:61]: geeze that is unforntunate but I commend you on this hackery 🫡 haha

Comment (Adamj1232) [reply packages/web3auth/src/index.ts:61]: Right?! Really surprising they dont have any config for the z-index of the modal. I created a feature request with their team to get this added - https://github.com/Web3Auth/web3auth-web/issues/1018

File: packages/uauth/tsconfig.json [hunk 2]
```diff
@@ -1,11 +1,12 @@
 {
   "extends": "../../tsconfig.json",
   "include": ["src/**/*"],
-  
+
   "compilerOptions": {
     "outDir": "dist",
     "rootDir": "src",
     "declarationDir": "dist",
+    "allowSyntheticDefaultImports": true,
```
[the remark this answers is not in the document]
Comment (Adamj1232) [reply packages/uauth/tsconfig.json]: Removed, added accidentally
